micronaut:
  application:
    name: kafka

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: admin
    password: password
    schema-generator: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

kafka:
  bootstrap:
    servers: localhost:9092
  producers:
    default:
      retries: 3